name: OCI Instance Grabber

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-grabber:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --no-progress

      - name: Run OCI Host Capacity Script
        env:
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_USER_ID: ${{ secrets.OCI_USER_OCID }}
          OCI_USER_OCID: ${{ secrets.OCI_USER_OCID }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_OCID }}
          OCI_TENANCY_OCID: ${{ secrets.OCI_TENANCY_OCID }}
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_OCID }}
          OCI_SUBNET_OCID: ${{ secrets.OCI_SUBNET_OCID }}
          OCI_KEY_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_KEY_CONTENT: ${{ secrets.OCI_KEY_CONTENT }}
        run: php index.php
